---
- hosts: localhost
  connection: local
  become: true

  tasks:
  - name: install packages
    package:
      name:
        - htop
        - tmux
        - python3-psutil
  - name: copy wallpaper file
    copy:
      src: files/beardedskull.jpg
      dest: /usr/share/backgrounds/ansible-wallpaper.jpg
      owner: root
      group: root

  - name: set wallpaper
    become_user: joshua
    dconf:
      key: "/org/gnome/desktop/background/picture-uri"
      value: "'file:///usr/share/backgrounds/ansible-wallpaper.jpg"

  - name: set wallpaper dark
    become_user: joshua
    dconf:
      key: "/org/gnome/desktop/background/picture-uri-dark"
      value: "'file:///usr/share/backgrounds/ansible-wallpaper.jpg"

  - name: set login wallpaper
    become_user: joshua
    dconf:
      key: "/org/gnome/desktop/screensaver/picture-uri"
      value: "'file:///usr/share/backgrounds/ansible-wallpaper.jpg"

  - name: set wallpaper position
    become_user: joshua
    dconf:
      key: "/org/gnome/desktop/background/picture-options"
      value: "'zoom'"
